version: '3.8'

services:
  rubberduckie-app:
    image: maven:3.9-eclipse-temurin-17
    container_name: rubberduckie-container
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - maven-repo:/root/.m2
    working_dir: /app
    command: sh -c "mvn clean package -DskipTests && java -jar target/rubberduckie-1.0-SNAPSHOT.jar"
    restart: unless-stopped
    networks:
      - rubberduckie-network

networks:
  rubberduckie-network:
    driver: bridge

volumes:
  maven-repo: